# Generated by Django 4.2.11 on 2024-04-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=256, unique=True)),
                ("data", models.BinaryField()),
                ("html", models.TextField(verbose_name="HTML")),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True)),
                ("organizer", models.CharField(blank=True, max_length=64)),
                ("path", models.CharField(max_length=256)),
                ("time", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("d", "Directory"), ("f", "File"), ("e", "Error")], max_length=1
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=256)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="fudan.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
