# Generated by Django 4.2.11 on 2024-04-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fudan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="html",
        ),
        migrations.AddField(
            model_name="menulink",
            name="target_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent",
                to="fudan.document",
            ),
        ),
        migrations.AddField(
            model_name="menulink",
            name="target_menu",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent",
                to="fudan.menu",
            ),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="path",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="type",
            field=models.CharField(
                choices=[("d", "Directory"), ("f", "File"), ("e", "Error")],
                db_index=True,
                max_length=1,
            ),
        ),
    ]
