# Generated by Django 4.2.11 on 2024-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fudan", "0002_remove_document_html_menulink_target_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulink",
            name="path",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="type",
            field=models.CharField(
                choices=[("d", "Directory"), ("f", "File"), ("e", "Error")], max_length=1
            ),
        ),
    ]
