# Generated by Django 4.2.11 on 2024-04-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fudan", "0003_alter_menulink_path_alter_menulink_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulink",
            name="target_document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents",
                to="fudan.document",
            ),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="target_menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents",
                to="fudan.menu",
            ),
        ),
    ]
