# Generated by Django 4.2.11 on 2024-04-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fudan", "0004_alter_menulink_target_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
