# Generated by Django 4.2.11 on 2024-04-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fudan", "0005_document_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulink",
            name="target_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents",
                to="fudan.document",
            ),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="target_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parents",
                to="fudan.menu",
            ),
        ),
    ]
