# Generated by Django 4.2.11 on 2024-04-19 01:26

import ascii.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fudan", "0006_alter_menulink_target_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="text",
            field=ascii.core.fields.NonStrippingTextField(),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="text",
            field=ascii.core.fields.NonStrippingCharField(blank=True, max_length=256),
        ),
    ]
