# Generated by Django 4.2.11 on 2024-05-03 02:02

import ascii.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fudan", "0007_alter_document_text_alter_menulink_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScratchFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("text", ascii.core.fields.NonStrippingTextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
