# Generated by Django 5.1.1 on 2024-09-30 21:43

import ascii.mozz.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField()),
                ("published_date", models.DateField(db_index=True, default=datetime.date.today)),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to=ascii.mozz.models.upload_to)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("txt", "txt"), ("xbin", "xbin"), ("png", "png")], max_length=16
                    ),
                ),
                (
                    "font_name",
                    models.CharField(
                        blank=True,
                        choices=[("menlo", "Menlo"), ("topaz_2plus", "Amiga Topaz 2+")],
                        max_length=16,
                    ),
                ),
                (
                    "image_x1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ascii.mozz.models.upload_to,
                        verbose_name="Image (x1)",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "published_date"), name="artpost_slug_published_date"
                    )
                ],
            },
        ),
    ]
