# Generated by Django 5.1.1 on 2024-10-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artpost",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.RemoveConstraint(
            model_name="artpost",
            name="artpost_slug_published_date",
        ),
        migrations.RenameField(
            model_name="artpost",
            old_name="published_date",
            new_name="date",
        ),
        migrations.AlterField(
            model_name="artpost",
            name="file_type",
            field=models.CharField(
                choices=[("text", "plaintext"), ("xbin", "xbin"), ("png", "png")], max_length=16
            ),
        ),
        migrations.AddConstraint(
            model_name="artpost",
            constraint=models.UniqueConstraint(fields=("slug", "date"), name="artpost_slug_date"),
        ),
    ]
