# Generated by Django 5.1.1 on 2024-10-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mozz", "0004_alter_artpost_file_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artpost",
            old_name="grid_columns",
            new_name="grid_column_span",
        ),
        migrations.RenameField(
            model_name="artpost",
            old_name="grid_rows",
            new_name="grid_row_span",
        ),
    ]
