# Generated by Django 5.1.1 on 2024-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0008_alter_artpost_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artpost",
            name="file_type",
            field=models.CharField(
                choices=[("text", "plaintext"), ("xbin", "XBin"), ("other", "other")], max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="artpost",
            name="font_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("menlo", "Menlo"),
                    ("topaz_2plus", "Amiga Topaz 2+"),
                    ("jgs", "Jgs"),
                    ("custom", "Custom"),
                ],
                max_length=16,
            ),
        ),
    ]
