# Generated by Django 5.1.1 on 2024-10-07 19:26

import ascii.mozz.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mozz", "0009_alter_artpost_file_type_alter_artpost_font_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtPostAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("file", models.FileField(upload_to=ascii.mozz.models.upload_attachment_to)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mozz.artpost",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
