# Generated by Django 5.1.1 on 2024-10-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mozz", "0010_artpostattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrollFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="artpostattachment",
            options={"ordering": ["id"]},
        ),
    ]
