# Generated by Django 5.1.1 on 2024-10-10 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0013_artpost_featured"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artpost",
            old_name="featured",
            new_name="favorite",
        ),
    ]
