# Generated by Django 5.1.1 on 2025-11-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0014_rename_featured_artpost_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artpost",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("text", "Plain text"),
                    ("ans", "Ans"),
                    ("asc", "Asc"),
                    ("xbin", "XBin"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="artpost",
            name="font_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("menlo", "Menlo"),
                    ("topaz_2plus", "Amiga Topaz 2+"),
                    ("jgs", "Jgs"),
                    ("cp437", "IBM CP437"),
                    ("custom", "Custom"),
                ],
                max_length=16,
            ),
        ),
    ]
