# Generated by Django 5.1.1 on 2025-11-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0015_alter_artpost_file_type_alter_artpost_font_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artpost",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("text", ".txt"),
                    ("ans", ".ans"),
                    ("asc", ".asc"),
                    ("xbin", ".xbin"),
                    ("other", "other"),
                ],
                max_length=16,
            ),
        ),
    ]
