# Generated by Django 5.1.1 on 2025-11-21 22:34

import ascii.core.backends.storage
import ascii.mozz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mozz", "0016_alter_artpost_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artpost",
            name="file",
            field=models.FileField(
                storage=ascii.core.backends.storage.OverwriteFileSystemStorage(),
                upload_to=ascii.mozz.models.upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="artpost",
            name="image_x1",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=ascii.core.backends.storage.OverwriteFileSystemStorage(),
                upload_to=ascii.mozz.models.upload_to,
                verbose_name="Image (x1)",
            ),
        ),
    ]
