# Generated by Django 5.2.10 on 2026-01-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0017_alter_artpost_file_alter_artpost_image_x1"),
    ]

    operations = [
        migrations.AddField(
            model_name="artpost",
            name="sauce_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
