# Generated by Django 5.2.10 on 2026-01-21 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0018_artpost_sauce_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="artpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
