# Generated by Django 5.2.10 on 2026-01-22 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0019_artpost_created_at_artpost_updated_at"),
        ("textmode", "0033_artpack_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="artpost",
            name="artfile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="textmode.artfile",
            ),
        ),
        migrations.AddField(
            model_name="artpost",
            name="pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="textmode.artpack",
            ),
        ),
    ]
