# Generated by Django 5.2.10 on 2026-01-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0020_artpost_artfile_artpost_pack"),
    ]

    operations = [
        migrations.AddField(
            model_name="artpost",
            name="artfile_name",
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
