# Generated by Django 5.2.10 on 2026-01-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0021_artpost_artfile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artpost",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
