# Generated by Django 5.2.16 on 2026-09-12 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0022_alter_artpost_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScrollFile",
        ),
    ]
