# Generated by Django 5.2.16 on 2026-09-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mozz", "0023_delete_scrollfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrollFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("text", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
