# Generated by Django 5.1.1 on 2025-05-11 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mltartwork",
            name="mlt_file",
        ),
        migrations.RemoveField(
            model_name="mltartwork",
            name="title",
        ),
        migrations.CreateModel(
            name="MLTSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256)),
                (
                    "mlt_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="huku.mltfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="mltartwork",
            name="section",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artworks",
                to="huku.mltsection",
            ),
            preserve_default=False,
        ),
    ]
