# Generated by Django 5.1.1 on 2025-05-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0002_remove_mltartwork_mlt_file_remove_mltartwork_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mltartwork",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="mltsection",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
