# Generated by Django 5.1.1 on 2025-05-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0003_mltartwork_order_mltsection_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mltfile",
            name="last_update_date",
        ),
        migrations.AddField(
            model_name="mltfile",
            name="last_update",
            field=models.DateField(blank=True, null=True),
        ),
    ]
