# Generated by Django 5.1.1 on 2025-05-12 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0004_remove_mltfile_last_update_date_mltfile_last_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mltartwork",
            options={"ordering": ["order", "id"], "verbose_name": "MLTArtwork"},
        ),
        migrations.AlterModelOptions(
            name="mltdirectory",
            options={"verbose_name": "MLTDirectory", "verbose_name_plural": "MLTDirectories"},
        ),
        migrations.AlterModelOptions(
            name="mltfile",
            options={"verbose_name": "MLTFile"},
        ),
        migrations.AlterModelOptions(
            name="mltsection",
            options={"ordering": ["order", "id"], "verbose_name": "MLTSection"},
        ),
        migrations.RenameField(
            model_name="mltfile",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="mltdirectory",
            name="directory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subdirectories",
                to="huku.mltdirectory",
            ),
        ),
        migrations.AddField(
            model_name="mltfile",
            name="data",
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mltfile",
            name="nsfw",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mltartwork",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artwork",
                to="huku.mltsection",
            ),
        ),
    ]
