# Generated by Django 5.1.1 on 2025-05-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0005_alter_mltartwork_options_alter_mltdirectory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mltfile",
            name="decoding_error",
            field=models.BooleanField(default=False),
        ),
    ]
