# Generated by Django 5.1.1 on 2025-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0006_mltfile_decoding_error"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mltdirectory",
            old_name="directory",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="mltfile",
            old_name="directory",
            new_name="parent",
        ),
        migrations.AlterField(
            model_name="mltfile",
            name="nsfw",
            field=models.BooleanField(default=False, verbose_name="NSFW"),
        ),
    ]
