# Generated by Django 5.1.1 on 2025-05-12 14:34

import ascii.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0007_rename_directory_mltdirectory_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mltsection",
            name="mlt_file",
        ),
        migrations.CreateModel(
            name="MLTItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("heading", "Heading"), ("artwork", "Artwork")], max_length=8
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("heading", models.CharField(blank=True, max_length=256)),
                ("text", ascii.core.fields.NonStrippingTextField(blank=True)),
                (
                    "mlt_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="huku.mltfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "MLTItem",
                "ordering": ["order", "mlt_file"],
            },
        ),
        migrations.DeleteModel(
            name="MLTArtwork",
        ),
        migrations.DeleteModel(
            name="MLTSection",
        ),
    ]
