# Generated by Django 5.1.1 on 2025-05-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0008_remove_mltsection_mlt_file_mltitem_delete_mltartwork_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mltdirectory",
            options={"verbose_name": "MLT Directory", "verbose_name_plural": "MLT Directories"},
        ),
        migrations.AlterModelOptions(
            name="mltfile",
            options={"verbose_name": "MLT File"},
        ),
        migrations.AlterModelOptions(
            name="mltitem",
            options={"ordering": ["order", "mlt_file"], "verbose_name": "MLT Item"},
        ),
        migrations.AddField(
            model_name="mltitem",
            name="line_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
