# Generated by Django 5.1.1 on 2025-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0009_alter_mltdirectory_options_alter_mltfile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mltitem",
            name="item_type",
            field=models.CharField(
                choices=[("heading", "Heading"), ("artwork", "Artwork")],
                db_index=True,
                max_length=8,
            ),
        ),
    ]
