# Generated by Django 5.1.1 on 2025-05-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0010_alter_mltitem_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mltfile",
            name="artwork_count",
            field=models.IntegerField(default=0),
        ),
    ]
