# Generated by Django 5.1.1 on 2025-05-14 15:21

import ascii.huku.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0011_mltfile_artwork_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="mltitem",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to=ascii.huku.models.upload_to),
        ),
    ]
