# Generated by Django 5.1.1 on 2025-05-28 02:55

import ascii.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0012_mltitem_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mltitem",
            options={"ordering": ["mlt_file", "order"], "verbose_name": "MLT Item"},
        ),
        migrations.AddField(
            model_name="mltitem",
            name="slug",
            field=models.SlugField(default=ascii.core.utils.gen_random_slug, unique=True),
        ),
    ]
