# Generated by Django 5.1.1 on 2025-05-28 03:21

import ascii.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0013_alter_mltitem_options_mltitem_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="mltdirectory",
            name="slug",
            field=models.SlugField(default=ascii.core.utils.gen_random_slug, unique=True),
        ),
        migrations.AddField(
            model_name="mltfile",
            name="slug",
            field=models.SlugField(default=ascii.core.utils.gen_random_slug, unique=True),
        ),
    ]
