# Generated by Django 5.1.1 on 2025-05-30 01:49

import ascii.core.fields
import ascii.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huku", "0014_mltdirectory_slug_mltfile_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mltfile",
            name="slug",
        ),
        migrations.CreateModel(
            name="MLTSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=256)),
                ("nsfw", models.BooleanField(default=False, verbose_name="NSFW")),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("artwork_count", models.IntegerField(default=0)),
                (
                    "mlt_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="huku.mltfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "MLT Section",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MLTArtwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(default=ascii.core.utils.gen_random_slug, unique=True)),
                ("nsfw", models.BooleanField(default=False, verbose_name="NSFW")),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("text", ascii.core.fields.NonStrippingTextField(blank=True)),
                ("line_count", models.IntegerField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artwork",
                        to="huku.mltsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "MLT Artwork",
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="MLTItem",
        ),
    ]
