# Generated by Django 4.2.11 on 2024-08-21 02:41

import ascii.textmode.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("is_fileid", models.BooleanField(default=False)),
                ("raw_file", models.FileField(upload_to=ascii.textmode.models.upload_to_raw)),
                (
                    "image_tn",
                    models.ImageField(
                        upload_to=ascii.textmode.models.upload_to_tn,
                        verbose_name="Image (thumbnail)",
                    ),
                ),
                (
                    "image_x1",
                    models.ImageField(
                        upload_to=ascii.textmode.models.upload_to_x1, verbose_name="Image (x1)"
                    ),
                ),
                (
                    "image_x2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ascii.textmode.models.upload_to_x2,
                        verbose_name="Image (x2)",
                    ),
                ),
                ("sauce_data", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(blank=True, db_index=True, max_length=35)),
                ("author", models.CharField(blank=True, db_index=True, max_length=20)),
                ("group", models.CharField(blank=True, db_index=True, max_length=20)),
                ("date", models.DateField(blank=True, db_index=True, null=True)),
                ("filesize", models.IntegerField(db_index=True, default=0)),
                (
                    "datatype",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Character"),
                            (2, "Bitmap"),
                            (3, "Vector"),
                            (4, "Audio"),
                            (5, "BinaryText"),
                            (6, "XBin"),
                            (7, "Archive"),
                            (8, "Executable"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "filetype",
                    models.IntegerField(
                        choices=[
                            ("None", "None"),
                            ("ASCII", "Ascii"),
                            ("ANSi", "Ansi"),
                            ("ANSiMation", "Ansimation"),
                            ("RIP script", "Ripscript"),
                            ("PCBoard", "Pcboard"),
                            ("Avatar", "Avatar"),
                            ("HTML", "Html"),
                            ("Source", "Source"),
                            ("TundraDraw", "Tundradraw"),
                            ("GIF", "Gif"),
                            ("PCX", "Pcx"),
                            ("LBM/IFF", "Lbm"),
                            ("TGA", "Tga"),
                            ("FLI", "Fli"),
                            ("FLC", "Flc"),
                            ("BMP", "Bmp"),
                            ("GL", "Gl"),
                            ("DL", "Dl"),
                            ("WPG Bitmap", "Wpgbitmap"),
                            ("PNG", "Png"),
                            ("JPG/JPeg", "Jpg"),
                            ("MPG", "Mpg"),
                            ("AVI", "Avi"),
                            ("DXF", "Dxf"),
                            ("DWG", "Dwg"),
                            ("WPG Vector", "Wpgvector"),
                            ("3DS", "Threeds"),
                            ("MOD", "Mod"),
                            ("669", "Sixsixnine"),
                            ("STM", "Stm"),
                            ("S3M", "S3M"),
                            ("MTM", "Mtm"),
                            ("FAR", "Far"),
                            ("ULT", "Ult"),
                            ("AMF", "Amf"),
                            ("DMF", "Dmf"),
                            ("OKT", "Okt"),
                            ("ROL", "Rol"),
                            ("CMF", "Cmf"),
                            ("MID", "Mid"),
                            ("SADT", "Sadt"),
                            ("VOC", "Voc"),
                            ("WAV", "Wav"),
                            ("SMP8", "Smp8"),
                            ("SMP8S", "Smp8S"),
                            ("SMP16", "Smp16"),
                            ("SMP16S", "Smp16S"),
                            ("PATCH8", "Patch8"),
                            ("PATCH16", "Patch16"),
                            ("XM", "Xm"),
                            ("HSC", "Hsc"),
                            ("IT", "It"),
                            ("binary", "Binarytext"),
                            ("XBin", "Xbin"),
                            ("ZIP", "Zip"),
                            ("ARJ", "Arj"),
                            ("LZH", "Lzh"),
                            ("ARC", "Arc"),
                            ("TAR", "Tar"),
                            ("ZOO", "Zoo"),
                            ("RAR", "Rar"),
                            ("UC2", "Uc2"),
                            ("PAK", "Pak"),
                            ("SQZ", "Sqz"),
                            ("executable", "Executable"),
                        ],
                        db_index=True,
                    ),
                ),
                ("pixel_width", models.IntegerField(blank=True, db_index=True, null=True)),
                ("pixel_height", models.IntegerField(blank=True, db_index=True, null=True)),
                ("character_width", models.IntegerField(blank=True, db_index=True, null=True)),
                ("number_of_lines", models.IntegerField(blank=True, db_index=True, null=True)),
                ("ice_colors", models.BooleanField(blank=True, db_index=True, null=True)),
                (
                    "letter_spacing",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "No Preference"), (1, "8 pixel"), (2, "9 pixel")],
                        db_index=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_fileid", "name"],
            },
        ),
        migrations.CreateModel(
            name="ArtFileTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("artist", "Artist"), ("content", "Content"), ("group", "Group")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ArtPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("year", models.IntegerField()),
                ("zip_file", models.FileField(upload_to=ascii.textmode.models.upload_to_zip)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="artfiletag",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique_artfiletag_category_name"
            ),
        ),
        migrations.AddField(
            model_name="artfile",
            name="pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artfiles",
                to="textmode.artpack",
            ),
        ),
        migrations.AddField(
            model_name="artfile",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="artfiles", to="textmode.artfiletag"
            ),
        ),
        migrations.AddConstraint(
            model_name="artfile",
            constraint=models.UniqueConstraint(
                fields=("name", "pack"), name="unique_artfile_name_pack"
            ),
        ),
    ]
