# Generated by Django 4.2.11 on 2024-08-01 19:21

import ascii.textmode.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artisttag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="artpack",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="contenttag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="grouptag",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="artfile",
            name="raw",
            field=models.FileField(default="", upload_to=ascii.textmode.models.upload_to_raw),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artpack",
            name="fileid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="textmode.artfile",
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="artist_tags",
            field=models.ManyToManyField(
                blank=True, related_name="art_files", to="textmode.artisttag"
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="content_tags",
            field=models.ManyToManyField(
                blank=True, related_name="art_files", to="textmode.contenttag"
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="group_tags",
            field=models.ManyToManyField(
                blank=True, related_name="art_files", to="textmode.grouptag"
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="image_tn",
            field=models.ImageField(
                upload_to=ascii.textmode.models.upload_to_tn, verbose_name="Image (thumbnail)"
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="image_x1",
            field=models.ImageField(
                upload_to=ascii.textmode.models.upload_to_x1, verbose_name="Image (x1)"
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="image_x2",
            field=models.ImageField(
                upload_to=ascii.textmode.models.upload_to_x2, verbose_name="Image (x2)"
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="art_files",
                to="textmode.artpack",
            ),
        ),
        migrations.AddConstraint(
            model_name="artfile",
            constraint=models.UniqueConstraint(
                fields=("name", "pack"), name="unique_artfile_name_pack"
            ),
        ),
    ]
