# Generated by Django 4.2.11 on 2024-08-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0004_remove_artpack_fileid_artfile_is_fileid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artfile",
            options={"ordering": ["-is_fileid", "name"]},
        ),
    ]
