# Generated by Django 4.2.11 on 2024-08-21 03:30

import ascii.textmode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0004_artfile_created_at_artpack_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artfile",
            name="image_tn",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ascii.textmode.models.upload_to_tn,
                verbose_name="Image (thumbnail)",
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="image_x1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=ascii.textmode.models.upload_to_x1,
                verbose_name="Image (x1)",
            ),
        ),
    ]
