# Generated by Django 4.2.11 on 2024-08-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0005_alter_artfile_image_tn_alter_artfile_image_x1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artfile",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="artfile",
            name="filesize",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
