# Generated by Django 4.2.11 on 2024-09-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0011_artfile_font_name_alter_artfile_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artfile",
            name="font_name",
            field=models.CharField(blank=True, db_index=True, default="", max_length=50),
            preserve_default=False,
        ),
    ]
