# Generated by Django 4.2.11 on 2024-09-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0012_alter_artfile_font_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="artfile",
            name="aspect_ratio",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "No Preference"), (1, "Stretch"), (2, "Square")],
                db_index=True,
                null=True,
            ),
        ),
    ]
