# Generated by Django 4.2.11 on 2024-09-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0014_alter_artfile_filetype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artfile",
            name="image_x2",
        ),
    ]
