# Generated by Django 5.1.1 on 2024-09-18 13:24

import ascii.textmode.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0016_alter_artfile_filetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artfile",
            name="image_tn",
            field=models.ImageField(
                blank=True,
                max_length=130,
                null=True,
                upload_to=ascii.textmode.models.upload_to_tn,
                verbose_name="Image (thumbnail)",
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="image_x1",
            field=models.ImageField(
                blank=True,
                max_length=130,
                null=True,
                upload_to=ascii.textmode.models.upload_to_x1,
                verbose_name="Image (x1)",
            ),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="name",
            field=models.CharField(db_index=True, max_length=130),
        ),
        migrations.AlterField(
            model_name="artfile",
            name="raw_file",
            field=models.FileField(max_length=130, upload_to=ascii.textmode.models.upload_to_raw),
        ),
    ]
