# Generated by Django 5.1.1 on 2024-09-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0017_alter_artfile_image_tn_alter_artfile_image_x1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artfiletag",
            name="artfile_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
