# Generated by Django 5.1.1 on 2024-09-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0018_artfiletag_artfile_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="artfile",
            name="is_joint",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
