# Generated by Django 5.1.1 on 2024-09-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0019_artfile_is_joint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.SlugField()),
                ("title", models.TextField()),
                (
                    "artfiles",
                    models.ManyToManyField(
                        blank=True, related_name="galleries", to="textmode.artfile"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
