# Generated by Django 5.1.1 on 2024-09-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0022_gallery_visible"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gallery",
            old_name="title",
            new_name="description",
        ),
    ]
