# Generated by Django 5.1.1 on 2024-09-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0023_rename_title_gallery_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
