# Generated by Django 5.1.1 on 2024-09-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0024_alter_gallery_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="visible",
            field=models.BooleanField(default=False),
        ),
    ]
