# Generated by Django 5.1.1 on 2024-09-23 01:12

import ascii.textmode.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0025_alter_gallery_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="slug",
            field=models.SlugField(default=ascii.textmode.models.gen_slug, unique=True),
        ),
    ]
