# Generated by Django 5.1.1 on 2024-09-24 01:45

import ascii.textmode.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0026_gallery_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(default=ascii.textmode.models.gen_slug, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("visible", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ArtCollectionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.IntegerField(db_index=True, default=0)),
                (
                    "artfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="textmode.artfile"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="textmode.artcollection"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="artcollection",
            name="artfiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="textmode.ArtCollectionMapping",
                to="textmode.artfile",
            ),
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
    ]
