# Generated by Django 5.1.1 on 2024-09-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0029_alter_artcollection_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artcollectionmapping",
            options={"ordering": ["order"]},
        ),
    ]
