# Generated by Django 5.1.1 on 2024-09-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("textmode", "0030_alter_artcollectionmapping_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="artcollection",
            name="order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
