# Generated by Django 5.2.10 on 2026-01-22 03:44

import ascii.textmode.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0031_artcollection_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artpack",
            name="zip_file",
            field=models.FileField(
                blank=True, null=True, upload_to=ascii.textmode.models.upload_to_zip
            ),
        ),
    ]
