# Generated by Django 5.2.10 on 2026-01-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0032_alter_artpack_zip_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="artpack",
            name="visible",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
