# Generated by Django 5.2.10 on 2026-01-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("textmode", "0033_artpack_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="artfile",
            name="is_internal",
            field=models.BooleanField(default=False),
        ),
    ]
