# Generated by Django 5.2.10 on 2026-01-20 22:15

import ascii.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authtoken",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="authtoken",
            name="key",
            field=models.CharField(
                default=ascii.users.models.generate_key,
                max_length=40,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
