# Generated by Django 5.2.10 on 2026-01-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_created_authtoken_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtoken",
            name="key",
            field=models.CharField(blank=True, max_length=40, primary_key=True, serialize=False),
        ),
    ]
