# Generated by Django 4.2.11 on 2024-04-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=256, unique=True)),
                ("data", models.BinaryField()),
                ("html", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True)),
                ("path", models.CharField(max_length=256)),
                ("time", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("d", "Document"), ("f", "File"), ("e", "Error")], max_length=1
                    ),
                ),
                ("text", models.CharField(max_length=256)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="fundan.menu",
                    ),
                ),
            ],
        ),
    ]
