# Generated by Django 4.2.11 on 2024-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menulink",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="menulink",
            name="organizer",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="document",
            name="html",
            field=models.TextField(verbose_name="HTML"),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="text",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
