# Generated by Django 4.2.11 on 2024-04-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh-cn", "Chinese Simplified"), ("en", "English")], max_length=10
                    ),
                ),
                ("original", models.TextField(db_index=True)),
                ("translated", models.TextField(blank=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=("original", "language"), name="translation_unique_text"
            ),
        ),
    ]
