# Generated by Django 4.2.11 on 2024-04-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="language",
            field=models.CharField(choices=[("zh-cn", "zh-cn"), ("en", "en")], max_length=10),
        ),
    ]
